name = "yodel"
version = "0.1.0"

description = "Yodel: Yo-de-lay-ee-config!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "fluximus-prime", repo = "yodel" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
# glaml = ">= 1.0.1 and < 2.0.0"
glaml = { path = "../glaml" }
envoy = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
tom = ">= 0.3.0 and < 2.0.0"
birl = ">= 1.7.1 and < 2.0.0"

[dev-dependencies]
# startest = ">= 0.5.0 and < 1.0.0"
startest = { path = "../startest" }
