name: Gleam
description: Run Gleam Tests

on:
  workflow_call:

jobs:
  test:
    name: Gleam
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup BEAM Environment
        uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Restore Build Cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: |
            ~/.cache/gleam
            build
          key: ${{ runner.os }}-gleam-${{ hashFiles('**/gleam.toml') }}
          restore-keys: |
            ${{ runner.os }}-gleam-

      - name: Download Dependencies
        run: gleam deps download

      - name: Run Tests
        run: gleam test
