name: Gleam
description: Run Gleam Tests

on:
  workflow_call:

jobs:
  test:
    name: Gleam
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup BEAM Environment
        uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Restore Build Cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            ~/.cache/gleam
            build
          key: ${{ runner.os }}-gleam-${{ hashFiles('**/gleam.toml') }}
          restore-keys: |
            ${{ runner.os }}-gleam-

      - name: Download Dependencies
        run: gleam deps download

      - name: Run Tests
        run: gleam test
