name: Markdown
description: Check Markdown Lint

on:
  workflow_call:
    inputs:
      markdownlint-version:
        required: false
        type: string
        default: "latest"

jobs:
  format:
    name: Markdown
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: latest

      - name: Lint Check
        run: npx markdownlint-cli2@${{ inputs.markdownlint-version }}
