name: Format Check & Test

on:
  push:
    branches:
      - master
      - main
      - renovate/**
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Format Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup BEAM Environment
        uses: erlef/setup-beam@8aa8a857c6be0daae6e97272bb299d5b942675a4 # v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Format Check
        run: gleam format --check src test

  test:
    name: Test
    needs: [ lint ]
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup BEAM Environment
        uses: erlef/setup-beam@8aa8a857c6be0daae6e97272bb299d5b942675a4 # v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Restore Build Cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: |
            ~/.cache/gleam
            build
          key: ${{ runner.os }}-gleam-${{ hashFiles('**/gleam.toml') }}
          restore-keys: |
            ${{ runner.os }}-gleam-

      - name: Download Dependencies
        run: gleam deps download

      - name: Run Tests
        run: gleam test --target erlang
