name: Lint & Test

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup BEAM Environment
        uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Lint Source
        run: gleam format --check src test

  test:
    name: Test
    needs: [ lint ]
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup BEAM Environment
        uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Restore Build Cache
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
        with:
          path: |
            ~/.cache/gleam
            build
          key: ${{ runner.os }}-gleam-${{ hashFiles('**/gleam.toml') }}
          restore-keys: |
            ${{ runner.os }}-gleam-

      - name: Download Dependencies
        run: gleam deps download

      - name: Run Tests
        run: gleam test --target erlang
