name: Workflow

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  prettier-format-check:
    name: Format Check
    uses: SnakeDoc/yodel/.github/workflows/prettier-format-check.yaml@f9c7b31f77115744b6676565d9f12a004817bffa # main

  markdown-lint-check:
    name: Lint Check
    uses: SnakeDoc/yodel/.github/workflows/markdown-lint-check.yaml@f9c7b31f77115744b6676565d9f12a004817bffa # main

  gleam-format-check:
    name: Format Check
    uses: SnakeDoc/yodel/.github/workflows/gleam-format-check.yaml@f9c7b31f77115744b6676565d9f12a004817bffa # main

  gleam-tests:
    name: Tests
    needs: [prettier-format-check, markdown-lint-check, gleam-format-check]
    uses: SnakeDoc/yodel/.github/workflows/gleam-tests.yaml@f9c7b31f77115744b6676565d9f12a004817bffa # main
